services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    volumes:
      - ./sqlserver_data:/var/opt/mssql/data
    user: "0:0"
    networks:
      - app-network

#  sqlclient:
#    image: mcr.microsoft.com/mssql-tools
#    depends_on:
#      - sqlserver
#    entrypoint: /bin/bash
#    tty: true
#    networks:
#      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile.proj
    ports:
      - 5032:8080
    container_name: app
    networks:
      - app-network
    environment:
      - AiCalendarAssistant/.env
    depends_on:
      - sqlserver
    
volumes:
  sqlserver_data:
networks:
  app-network:
    driver: bridge
