services:
  dotnet-dev:
    build: .
    image: my/dotnet9-dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - "2223:22"     # SSH
      - "5032:5032"   # ← publish 5032
    extra_hosts:
      - "host.docker.internal:host-gateway"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - '1433:1433'
    volumes:
      - ./sqlserver_data:/var/opt/mssql/data
    user: "0:0"
volumes:
  sqlserver_data:
