services:
  dotnet-dev:
    build: .
    image: my/dotnet9-dev
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"

